-- Optional optimizations only. This backend runs on plain PostgreSQL 16.
-- Have your database operator install extensions only if separately required.
-- No extensions are required by the supplied migrations or room-capacity checks.
