import 'stay_model.dart';
import 'booking_model.dart';

class MockData {
  static final List<StayModel> sampleStays = [
    StayModel(
      id: 'stay_1',
      title: 'Dreamy Forest Cabin',
      location: 'Manali, Himachal Pradesh',
      pricePerNight: 6250.0,
      rating: 4.92,
      reviewCount: 128,
      imageUrls: [
        'assets/images/cabin_1.jpg',
        'assets/images/cabin_1.jpg',
        'assets/images/cabin_1.jpg',
      ],
      category: 'Cabins',
      hostName: 'Alexander Vance',
      hostAvatar: 'assets/images/avatar_alex.jpg',
      isGuestFavorite: true,
      isStarHost: true,
      amenities: ['Fireplace', 'Mountain View', 'Fast WiFi', 'Kitchen', 'Free Parking', 'Jacuzzi'],
      description: 'Nestled amidst pine trees, this luxury timber cabin provides breathtaking views of snow-capped peaks and serene forest quietude.',
      lat: 32.2432,
      lng: 77.1892,
    ),
    StayModel(
      id: 'stay_2',
      title: 'Azure Horizon Villa',
      location: 'Santorini, Greece',
      pricePerNight: 34200.0,
      rating: 4.98,
      reviewCount: 94,
      imageUrls: [
        'assets/images/villa_1.jpg',
        'assets/images/villa_1.jpg',
      ],
      category: 'Amazing Pools',
      hostName: 'Elena Rostova',
      hostAvatar: 'assets/images/avatar_elena.jpg',
      isGuestFavorite: true,
      isStarHost: true,
      isFeatured: true,
      amenities: ['Infinity Pool', 'Sunset Terrace', 'Ocean View', 'Private Chef', 'Air Conditioning'],
      description: 'Iconic Aegean cliffside villa featuring an infinity pool merging into the sea and ultra-luxe Mediterranean interiors.',
      lat: 36.3932,
      lng: 25.4615,
    ),
    StayModel(
      id: 'stay_3',
      title: 'L\'Avenue Royale Suite',
      location: 'Saint-Germain, Paris',
      pricePerNight: 34800.0,
      rating: 4.90,
      reviewCount: 210,
      imageUrls: [
        'assets/images/suite_1.jpg',
        'assets/images/suite_1.jpg',
      ],
      category: 'Design',
      hostName: 'Jean-Luc Moreau',
      hostAvatar: 'assets/images/avatar_jean.jpg',
      isNew: true,
      amenities: ['Eiffel Tower View', 'Espresso Bar', 'Elevator', 'Balcony', 'Concierge Service'],
      description: 'Elegant Haussmannian apartment suite overlooking classic Parisian avenues with authentic antique art and modern comforts.',
      lat: 48.8566,
      lng: 2.3522,
    ),
    StayModel(
      id: 'stay_4',
      title: 'Oceanview Beachfront Villa',
      location: 'Anjuna, Goa',
      pricePerNight: 9850.0,
      rating: 4.85,
      reviewCount: 76,
      imageUrls: [
        'assets/images/beach_1.jpg',
        'assets/images/beach_1.jpg',
      ],
      category: 'Beachfront',
      hostName: 'Rohan Sharma',
      hostAvatar: 'assets/images/avatar_rohan.jpg',
      isGuestFavorite: true,
      amenities: ['Private Beach Access', 'Pool', 'Cocktail Bar', 'BBQ Grill', 'High-speed WiFi'],
      description: 'Step directly onto golden sands from your private teak deck. Enjoy tropical breezes, sunset cocktails, and seaside bliss.',
      lat: 15.5841,
      lng: 73.7443,
    ),
    StayModel(
      id: 'stay_5',
      title: 'The Glass Pavilion',
      location: 'Sausalito, California',
      pricePerNight: 69500.0,
      rating: 4.99,
      reviewCount: 152,
      imageUrls: [
        'assets/images/glass_1.jpg',
        'assets/images/glass_1.jpg',
      ],
      category: 'Design',
      hostName: 'Alexander Vance',
      hostAvatar: 'assets/images/avatar_alex.jpg',
      isStarHost: true,
      amenities: ['Panaromic Bay View', 'EV Charger', 'Sauna', 'Chef Kitchen', 'Wine Cellar'],
      description: 'Architectural masterpiece featuring floor-to-ceiling glass walls hovering above the redwood forest and San Francisco Bay.',
      lat: 37.8590,
      lng: -122.4853,
    ),
    StayModel(
      id: 'stay_6',
      title: 'Nordic Retreat Loft',
      location: 'Oslo, Norway',
      pricePerNight: 34200.0,
      rating: 4.95,
      reviewCount: 88,
      imageUrls: [
        'assets/images/nordic_1.jpg',
      ],
      category: 'Design',
      hostName: 'Sophia Lindqvist',
      hostAvatar: 'assets/images/avatar_alex.jpg',
      isStarHost: true,
      amenities: ['Finnish Sauna', 'Fireplace', 'Heated Floors', 'Workstation', 'City Skyline View'],
      description: 'Minimalist Scandinavian sanctuary with natural oak finishes, cozy fireplace corners, and serene fjords nearby.',
      lat: 59.9139,
      lng: 10.7522,
    ),
  ];

  static final List<BookingModel> sampleBookings = [
    BookingModel(
      id: 'bk_101',
      stay: sampleStays[0],
      checkIn: DateTime.now().add(const Duration(days: 5)),
      checkOut: DateTime.now().add(const Duration(days: 10)),
      adults: 2,
      children: 1,
      totalAmount: 3420.0,
      confirmationCode: 'SQ-8291XJ',
      status: BookingStatus.confirmed,
      guestName: 'Sarah & James',
      guestAvatar: 'assets/images/avatar_alex.jpg',
    ),
    BookingModel(
      id: 'bk_102',
      stay: sampleStays[5],
      checkIn: DateTime.now().add(const Duration(days: 14)),
      checkOut: DateTime.now().add(const Duration(days: 20)),
      adults: 1,
      children: 0,
      totalAmount: 2520.0,
      confirmationCode: 'SQ-9941NR',
      status: BookingStatus.upcoming,
      guestName: 'Michael Chen',
      guestAvatar: 'assets/images/avatar_jean.jpg',
    ),
  ];
}
