import { CorridorRegion } from '@prisma/client';

export interface CorridorSeedItem {
  slug: string;
  region: CorridorRegion;
  name: string;
  sortOrder: number;
  durationMinDays: number;
  durationMaxDays: number;
  distanceKm: number;
  stops: string[];
  theme: string;
  description: string;
  sourceName?: string;
  sourceUrl?: string;
  permits: string[];
  advisoryNotes?: string;
  badge?: string;
  highlights: string[];
  imageKey?: string;
}

export const CURATED_CORRIDORS: CorridorSeedItem[] = [
  // ─── 1. NORTH INDIA (10 CURATED CORRIDORS) ───
  {
    slug: 'himalayan-highlights-corridor',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Himalayan Highlights Corridor',
    sortOrder: 1,
    durationMinDays: 6,
    durationMaxDays: 8,
    distanceKm: 1250,
    stops: ['Delhi', 'Shimla', 'Kufri', 'Manali', 'Dharamshala', 'Dalhousie', 'Amritsar'],
    theme: 'Mountains, culture and classic North India',
    description: 'Snowy mountain views in season, hill towns, Tibetan culture and Punjabi food. A broad, multi-stop route inspired by the North India itinerary featured by Incredible India.',
    sourceName: 'Incredible India',
    sourceUrl: 'https://www.incredibleindia.org',
    permits: [],
    badge: 'Classic Mountain Circuit',
    highlights: ['Snowy mountain panoramas', 'Tibetan monasteries', 'Golden Temple Amritsar', 'Pine forest drives'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'spiti-valley-explorer',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Spiti Valley Explorer',
    sortOrder: 2,
    durationMinDays: 9,
    durationMaxDays: 13,
    distanceKm: 1100,
    stops: ['Shimla', 'Narkanda', 'Kalpa', 'Nako', 'Tabo', 'Kaza', 'Key', 'Manali'],
    theme: 'High-altitude adventure',
    description: 'Cold-desert scenery, monasteries, remote villages and dramatic mountain roads. Best for experienced drivers and suitably capable vehicles; seasonal access and route conditions must be checked.',
    sourceName: 'Himachal Tourism Official Website',
    sourceUrl: 'https://himachaltourism.gov.in',
    permits: ['Inner Line Permit for foreign nationals between Reckong Peo & Kaza'],
    advisoryNotes: 'Best attempted from June to October. High ground clearance and 4x4 campervans strongly advised.',
    badge: 'High-Altitude 4x4',
    highlights: ['Cold desert moonscapes', '1,000-year-old Tabo Monastery', 'Key Gompa', 'Chandratal high lake'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'lahaul-valley-escape',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Lahaul Valley Escape',
    sortOrder: 3,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 380,
    stops: ['Manali', 'Solang Valley', 'Atal Tunnel', 'Sissu', 'Keylong', 'Jispa'],
    theme: 'River valleys and mountain camping',
    description: 'A shorter Himalayan campervan journey with scenic stops, village visits and outdoor activities. Confirm suitable overnight sites rather than assuming roadside overnight parking is permitted.',
    sourceName: 'Himachal Tourism Official Website',
    sourceUrl: 'https://himachaltourism.gov.in',
    permits: [],
    advisoryNotes: 'Confirm pre-arranged campervan parking in Sissu and Jispa before arriving.',
    badge: 'Valley & Glaciers',
    highlights: ['Atal Tunnel engineering marvel', 'Sissu Waterfall', 'Bhaga River bank camping', 'Jispa stargazing'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'ganga-himalayan-foothills',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Ganga & Himalayan Foothills',
    sortOrder: 4,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 450,
    stops: ['Delhi', 'Haridwar', 'Rishikesh', 'Devprayag', 'Tehri'],
    theme: 'Riverside scenery and adventure',
    description: 'A good introductory route for shorter trips, with river confluences, spiritual landmarks, mountain views and opportunities for guided adventure activities.',
    sourceName: 'Uttarakhand Tourism',
    sourceUrl: 'https://uttarakhandtourism.gov.in',
    permits: [],
    badge: 'Riverside & Adventure',
    highlights: ['Ganga Aarti Rishikesh', 'Devprayag holy confluence', 'Tehri Dam reservoir water sports', 'Riverside campervan spots'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'kumaon-lakes-forests',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Kumaon Lakes & Forests',
    sortOrder: 5,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 520,
    stops: ['Delhi', 'Haldwani', 'Nainital', 'Bhimtal', 'Sattal', 'Mukteshwar'],
    theme: 'Lakes, forests and slow travel',
    description: 'A relaxed route for couples, families and first-time campervan travellers, with lake visits, viewpoints and village stays. Uttarakhand Tourism includes the Lakes of Kumaon among its tourism circuits.',
    sourceName: 'Uttarakhand Tourism',
    sourceUrl: 'https://uttarakhandtourism.gov.in',
    permits: [],
    badge: 'Lakes & Slow Living',
    highlights: ['Sattal birding & pine woods', 'Bhimtal lake promenade', 'Mukteshwar Himalayan view', 'Fruit orchards'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'rajasthan-royal-heritage',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Rajasthan Royal Heritage',
    sortOrder: 6,
    durationMinDays: 7,
    durationMaxDays: 9,
    distanceKm: 980,
    stops: ['Delhi', 'Jaipur', 'Pushkar', 'Jodhpur', 'Jaisalmer'],
    theme: 'Forts, desert and heritage',
    description: 'Explore historic cities, colourful markets, desert landscapes and local cuisine. Rajasthan has an extensive highway network connecting major destinations.',
    sourceName: 'Rajasthan Tourism',
    sourceUrl: 'https://www.tourism.rajasthan.gov.in',
    permits: [],
    badge: 'Heritage & Deserts',
    highlights: ['Amber Fort & Hawa Mahal', 'Pushkar sacred lake ghats', 'Mehrangarh Fort Jodhpur', 'Sam Sand Dunes camel trek'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'lakes-aravalli-retreat',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Lakes & Aravalli Retreat',
    sortOrder: 7,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 640,
    stops: ['Jaipur', 'Ajmer', 'Udaipur', 'Kumbhalgarh', 'Mount Abu'],
    theme: 'Lakes, palaces and hill retreats',
    description: 'A culture-and-comfort route combining heritage architecture, lakeside scenery and a hill-station finish. Well suited to a premium campervan itinerary.',
    sourceName: 'Rajasthan Tourism',
    sourceUrl: 'https://www.tourism.rajasthan.gov.in',
    permits: [],
    badge: 'Royal Palaces',
    highlights: ['Lake Pichola boat cruises', 'Kumbhalgarh Great Wall of India', 'Mount Abu Nakki Lake', 'Aravalli mountain drive'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'punjab-culture-trail',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Punjab Culture Trail',
    sortOrder: 8,
    durationMinDays: 4,
    durationMaxDays: 5,
    distanceKm: 490,
    stops: ['Chandigarh', 'Anandpur Sahib', 'Jalandhar', 'Amritsar', 'Wagah Border'],
    theme: 'Food, heritage and Punjabi culture',
    description: 'A road trip through religious landmarks, local food traditions and city attractions. Check current visitor-access rules and timings for border-area attractions before departure.',
    sourceName: 'Punjab Tourism',
    sourceUrl: 'https://punjabtourism.punjab.gov.in',
    permits: [],
    advisoryNotes: 'Check afternoon gate closure timings for Wagah Border Beating Retreat ceremony.',
    badge: 'Culinary & Heritage',
    highlights: ['Virasat-e-Khalsa museum', 'Golden Temple langar & illumination', 'Legendary GT Road dhabas', 'Wagah Border ceremony'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'mussoorie-forest-getaway',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Mussoorie & Forest Getaway',
    sortOrder: 9,
    durationMinDays: 3,
    durationMaxDays: 5,
    distanceKm: 280,
    stops: ['Dehradun', 'Mussoorie', 'Landour', 'Dhanaulti', 'Kanatal'],
    theme: 'Weekend escape and nature',
    description: 'A short getaway with forest drives, viewpoints, cafés and outdoor experiences. Check steep gradients, road widths and parking suitability for the actual campervan dimensions.',
    sourceName: 'Uttarakhand Tourism',
    sourceUrl: 'https://uttarakhandtourism.gov.in',
    permits: [],
    advisoryNotes: 'Roads in Landour are narrow; verify large campervan clearances or park at Mussoorie base.',
    badge: 'Quick Weekend Escape',
    highlights: ['Landour heritage bakehouse', 'Dhanaulti Eco Park deodars', 'Kanatal apple valley views', 'Kempty Falls'],
    imageKey: 'corridor_north_india',
  },
  {
    slug: 'garhwal-forest-village-trail',
    region: CorridorRegion.NORTH_INDIA,
    name: 'Garhwal Forest & Village Trail',
    sortOrder: 10,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 430,
    stops: ['Delhi', 'Kotdwar', 'Lansdowne', 'Pauri', 'Khirsu'],
    theme: 'Quiet villages and forest landscapes',
    description: 'A slower, less city-focused journey featuring pine forests, mountain viewpoints, village culture and relaxed stays. Best marketed around pre-arranged overnight parking or partner homestays with suitable vehicle access.',
    sourceName: 'Uttarakhand Tourism',
    sourceUrl: 'https://uttarakhandtourism.gov.in',
    permits: [],
    badge: 'Offbeat Villages',
    highlights: ['Lansdowne colonial oak woods', 'Khirsu snow peak vantage points', 'Garhwali village homestays', 'Pauri mountain sunrises'],
    imageKey: 'corridor_north_india',
  },

  // ─── 2. SOUTH INDIA (10 CURATED CORRIDORS) ───
  {
    slug: 'konkan-karnataka-coastal-escape',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Konkan–Karnataka Coastal Escape',
    sortOrder: 11,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 420,
    stops: ['Goa', 'Karwar', 'Gokarna', 'Murudeshwar', 'Udupi', 'Mangaluru'],
    theme: 'Beaches, coastal food and ocean views',
    description: 'Explore beach towns, coastal temples, seafood and scenic stretches of the Arabian Sea. Gokarna offers beaches and natural scenery.',
    sourceName: 'Karnataka Tourism',
    sourceUrl: 'https://www.karnatakatourism.org',
    permits: [],
    badge: 'Arabian Sea Coast',
    highlights: ['Om Beach & Kudle Beach', 'Murudeshwar colossal Shiva statue', 'Udupi authentic coastal cuisine', 'Maravanthe beach highway drive'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'coorg-coffee-country',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Coorg Coffee Country',
    sortOrder: 12,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 340,
    stops: ['Bengaluru', 'Mysuru', 'Kushalnagar', 'Madikeri', 'Talacauvery'],
    theme: 'Coffee estates and misty hills',
    description: 'A relaxed Western Ghats journey with coffee plantations, waterfalls, viewpoints and local food. Karnataka Tourism highlights Coorg for its coffee-growing landscape and hill scenery.',
    sourceName: 'Karnataka Tourism',
    sourceUrl: 'https://www.karnatakatourism.org',
    permits: [],
    badge: 'Coffee & Misty Hills',
    highlights: ['Coffee plantation campervan sites', 'Abbey Falls cascade', 'Namdroling Golden Temple', 'Talacauvery sacred source'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'chikmagalur-mountain-loop',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Chikmagalur Mountain Loop',
    sortOrder: 13,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 390,
    stops: ['Bengaluru', 'Hassan', 'Belur', 'Chikmagalur', 'Mullayanagiri', 'Kemmanagundi'],
    theme: 'Mountain drives and coffee trails',
    description: 'Discover highland viewpoints, coffee estates, waterfalls and historic Hoysala temples. The hill roads need vehicle-specific checks, especially on narrow or steep sections.',
    sourceName: 'Karnataka Tourism',
    sourceUrl: 'https://www.karnatakatourism.org',
    permits: [],
    advisoryNotes: 'Mullayanagiri peak approach road has steep hairpins; exercise caution in oversized RVs.',
    badge: 'High Peaks & Heritage',
    highlights: ['Mullayanagiri highest peak Karnataka', 'Hoysala temple architecture Belur', 'Baba Budangiri trails', 'Kemmanagundi waterfalls'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'royal-karnataka-heritage-trail',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Royal Karnataka Heritage Trail',
    sortOrder: 14,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 480,
    stops: ['Bengaluru', 'Srirangapatna', 'Mysuru', 'Hassan', 'Belur', 'Halebidu'],
    theme: 'Palaces, history and architecture',
    description: 'Combine Mysuru\'s royal heritage with temple architecture, historic towns and regional cuisine. This corridor suits culture-focused travellers who prefer shorter drives between sightseeing stops.',
    sourceName: 'Karnataka Tourism',
    sourceUrl: 'https://www.karnatakatourism.org',
    permits: [],
    badge: 'Royal Heritage',
    highlights: ['Mysore Palace grand illumination', 'Tipu Sultan Summer Palace Srirangapatna', 'Halebidu intricate soapstone carvings', 'Royal culinary tour'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'hampi-deccan-explorer',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Hampi & Deccan Explorer',
    sortOrder: 15,
    durationMinDays: 6,
    durationMaxDays: 8,
    distanceKm: 560,
    stops: ['Bengaluru', 'Chitradurga', 'Hampi', 'Aihole', 'Pattadakal', 'Badami'],
    theme: 'Ancient ruins and dramatic landscapes',
    description: 'Discover the ruins of the Vijayanagara Empire, monumental stone architecture, cave temples and the landscapes of the Deccan plateau. Karnataka Tourism lists Hampi, Badami, Aihole and Pattadakal among its heritage destinations.',
    sourceName: 'Karnataka Tourism',
    sourceUrl: 'https://www.karnatakatourism.org',
    permits: [],
    badge: 'UNESCO Heritage',
    highlights: ['Hampi stone chariot & boulder hills', 'Badami rock-cut cave temples', 'Pattadakal UNESCO temple group', 'Chitradurga massive stone fortress'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'kerala-tea-garden-route',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Kerala Tea Garden Route',
    sortOrder: 16,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 350,
    stops: ['Kochi', 'Munnar', 'Mattupetty', 'Marayoor', 'Thekkady'],
    theme: 'Tea estates and mountain scenery',
    description: 'Wind through tea-covered hills, visit viewpoints and explore the forested landscapes around Thekkady. Kerala Tourism\'s route and distance resources can help with detailed itinerary planning.',
    sourceName: 'Kerala Tourism',
    sourceUrl: 'https://www.keralatourism.org',
    permits: [],
    badge: 'Tea Plantations & Spice',
    highlights: ['Munnar emerald tea gardens', 'Marayoor natural sandalwood forest', 'Periyar Tiger Reserve boat safari', 'Cardamom & spice plantation visits'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'kerala-backwaters-beach-trail',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Kerala Backwaters & Beach Trail',
    sortOrder: 17,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 290,
    stops: ['Kochi', 'Marari', 'Alappuzha', 'Kumarakom', 'Varkala'],
    theme: 'Backwaters, beaches and slow travel',
    description: 'A relaxed coastal journey with village experiences, backwater cruises, beach sunsets and Kerala cuisine. Stay overnight at pre-arranged, campervan-friendly properties rather than assuming beach or waterside parking is allowed.',
    sourceName: 'Department of Tourism, Kerala',
    sourceUrl: 'https://www.keralatourism.org',
    permits: [],
    badge: 'Backwaters & Cliffs',
    highlights: ['Varkala red geological cliffs', 'Alappuzha canal system', 'Marari serene white sands', 'Vembanad Lake Kumarakom bird sanctuary'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'wayanad-forest-adventure',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Wayanad Forest Adventure',
    sortOrder: 18,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 240,
    stops: ['Mysuru', 'Gundlupet', 'Sulthan Bathery', 'Kalpetta', 'Vythiri'],
    theme: 'Forests, waterfalls and nature',
    description: 'Explore forested hills, plantations, caves and nature activities. Check forest-road access, wildlife-area restrictions and monsoon conditions before setting out.',
    sourceName: 'Kerala Tourism',
    sourceUrl: 'https://www.keralatourism.org',
    permits: [],
    advisoryNotes: 'Bandipur/Muthanga forest corridors enforce strict night traffic bans (9 PM to 6 AM). Plan drives accordingly.',
    badge: 'Rainforest & Wildlife',
    highlights: ['Bandipur forest elephant drive', 'Edakkal prehistoric cave art', 'Banasura Sagar earthen dam', 'Bamboo forest trails'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'nilgiri-hills-tea-country',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'Nilgiri Hills & Tea Country',
    sortOrder: 19,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 220,
    stops: ['Coimbatore', 'Coonoor', 'Ooty', 'Pykara', 'Gudalur'],
    theme: 'Hill stations and winding mountain roads',
    description: 'Enjoy tea gardens, cool-weather retreats, forest scenery and mountain viewpoints. Some sections are narrow and steep, so verify the route against campervan dimensions and local restrictions.',
    sourceName: 'Tamil Nadu Tourism',
    sourceUrl: 'https://www.tamilnadutourism.tn.gov.in',
    permits: [],
    badge: 'Misty Mountain Loops',
    highlights: ['Coonoor boutique tea estates', 'Pykara lake boating & falls', "Dolphin's Nose viewpoint", 'Nilgiri Mountain Railway corridor'],
    imageKey: 'corridor_south_india',
  },
  {
    slug: 'east-coast-culture-corridor',
    region: CorridorRegion.SOUTH_INDIA,
    name: 'East Coast Culture Corridor',
    sortOrder: 20,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 390,
    stops: ['Chennai', 'Mahabalipuram', 'Puducherry', 'Chidambaram', 'Thanjavur'],
    theme: 'Coastal drives, temples and heritage',
    description: 'Combine coastal scenery and historic architecture with French-influenced streets, traditional towns and Tamil cuisine. This route is well suited to travellers seeking culture alongside a coastal road trip.',
    sourceName: 'Tamil Nadu Tourism',
    sourceUrl: 'https://www.tamilnadutourism.tn.gov.in',
    permits: [],
    badge: 'East Coast Road (ECR)',
    highlights: ['Shore Temple Mahabalipuram', 'French Quarter White Town Puducherry', 'Chidambaram Nataraja Temple', 'Brihadisvara UNESCO Great Living Temple'],
    imageKey: 'corridor_south_india',
  },

  // ─── 3. GUJARAT & RAJASTHAN (5 CURATED CORRIDORS) ───
  {
    slug: 'great-rann-of-kutch-expedition',
    region: CorridorRegion.GUJARAT_RAJASTHAN,
    name: 'Great Rann of Kutch Expedition',
    sortOrder: 21,
    durationMinDays: 6,
    durationMaxDays: 8,
    distanceKm: 620,
    stops: ['Ahmedabad', 'Bhuj', 'Dhordo', 'Hodka', 'Mandvi'],
    theme: 'White desert and Kutchi culture',
    description: 'Experience the white salt landscape, traditional villages, handicrafts, local cuisine and the coast at Mandvi. Check seasonal access, event dates and designated parking before operating in the Rann.',
    sourceName: 'Gujarat Tourism',
    sourceUrl: 'https://www.gujarattourism.com',
    permits: ['Rann of Kutch entry permit required via official Gujarat Tourism portal'],
    advisoryNotes: 'Best experienced during full moon nights from November through February.',
    badge: 'White Salt Desert',
    highlights: ['White Rann salt desert moonwalk', 'Hodka artisan handicraft huts', 'Vijay Vilas Palace & Mandvi private beach', 'Bhuj mirror-work weaving'],
    imageKey: 'corridor_gujarat_rajasthan',
  },
  {
    slug: 'thar-desert-expedition',
    region: CorridorRegion.GUJARAT_RAJASTHAN,
    name: 'Thar Desert Expedition',
    sortOrder: 22,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 510,
    stops: ['Jodhpur', 'Osian', 'Pokhran', 'Jaisalmer', 'Sam Sand Dunes'],
    theme: 'Desert landscapes and stargazing',
    description: 'Build a desert-focused trip around sandstone towns, local culture, sunset experiences and guided dune activities. Overnight campervan stays should be arranged at authorised sites.',
    sourceName: 'Rajasthan Tourism',
    sourceUrl: 'https://www.tourism.rajasthan.gov.in',
    permits: [],
    badge: 'Dunes & Stargazing',
    highlights: ['Osian golden sand dunes', 'Jaisalmer living sandstone fort', 'Milky Way stargazing in deep desert', 'Sam sunset camel trek'],
    imageKey: 'corridor_gujarat_rajasthan',
  },
  {
    slug: 'royal-rajasthan-grand-circuit',
    region: CorridorRegion.GUJARAT_RAJASTHAN,
    name: 'Royal Rajasthan Grand Circuit',
    sortOrder: 23,
    durationMinDays: 9,
    durationMaxDays: 12,
    distanceKm: 820,
    stops: ['Jaipur', 'Ajmer', 'Pushkar', 'Jodhpur', 'Jaisalmer'],
    theme: 'Forts, palaces and desert nights',
    description: 'Visit Amber Fort, Pushkar Lake, Mehrangarh Fort and the golden sandstone city of Jaisalmer. Seamless highway network with verified night pit-stops.',
    sourceName: 'Rajasthan Tourism',
    sourceUrl: 'https://www.tourism.rajasthan.gov.in',
    permits: [],
    badge: 'Grand Royal Highway',
    highlights: ['Amber Fort & Jal Mahal', 'Pushkar sacred lake ghats', 'Mehrangarh Fort ramparts', 'Desert campfire hospitality'],
    imageKey: 'corridor_gujarat_rajasthan',
  },
  {
    slug: 'saurashtra-coastal-circuit',
    region: CorridorRegion.GUJARAT_RAJASTHAN,
    name: 'Saurashtra Coastal Circuit',
    sortOrder: 24,
    durationMinDays: 6,
    durationMaxDays: 8,
    distanceKm: 580,
    stops: ['Rajkot', 'Jamnagar', 'Dwarka', 'Porbandar', 'Somnath', 'Diu'],
    theme: 'Coastal roads, temples and beaches',
    description: 'Follow the Arabian Sea through pilgrimage destinations, coastal towns, beaches and seafood stops. Confirm entry rules and overnight arrangements in each destination.',
    sourceName: 'Gujarat Tourism',
    sourceUrl: 'https://www.gujarattourism.com',
    permits: [],
    badge: 'Arabian Sea Pilgrimage',
    highlights: ['Dwarkadhish ocean temple', 'Porbandar seaside promenade', 'Somnath evening light and sound show', 'Diu Portuguese fort & Nagoa beach'],
    imageKey: 'corridor_gujarat_rajasthan',
  },
  {
    slug: 'gir-wildlife-junagadh-trail',
    region: CorridorRegion.GUJARAT_RAJASTHAN,
    name: 'Gir Wildlife & Junagadh Trail',
    sortOrder: 25,
    durationMinDays: 4,
    durationMaxDays: 6,
    distanceKm: 390,
    stops: ['Rajkot', 'Junagadh', 'Sasan Gir', 'Somnath', 'Diu'],
    theme: 'Wildlife, heritage and coast',
    description: 'Pair an authorised Gir safari with Junagadh\'s heritage and a coastal stay near Somnath or Diu. Safari access is subject to availability and park rules.',
    sourceName: 'Gujarat Tourism',
    sourceUrl: 'https://www.gujarattourism.com',
    permits: ['Gir National Park jeep safari advance booking required via official portal'],
    advisoryNotes: 'Overnight campervan parking must be arranged outside national park restricted boundaries.',
    badge: 'Asiatic Lion Safari',
    highlights: ['Sasan Gir Asiatic lion safari', 'Uparkot Fort & Mahabat Maqbara', 'Somnath temple coastal drive', 'Diu island coastal camps'],
    imageKey: 'corridor_gujarat_rajasthan',
  },

  // ─── 4. NORTH EAST (5 CURATED CORRIDORS) ───
  {
    slug: 'meghalaya-waterfalls-living-root-bridges',
    region: CorridorRegion.NORTH_EAST,
    name: 'Meghalaya Waterfalls & Living Root Bridges',
    sortOrder: 26,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 360,
    stops: ['Guwahati', 'Shillong', 'Sohra', 'Mawlynnong', 'Dawki'],
    theme: 'Waterfalls, green valleys and village stays',
    description: 'Visit misty viewpoints, waterfalls, living-root bridges and the clear waters of the Umngot River. The Mawlynnong–Dawki route is featured by Meghalaya Tourism.',
    sourceName: 'Meghalaya Tourism',
    sourceUrl: 'https://www.meghalayatourism.in',
    permits: [],
    advisoryNotes: 'Allow extra driving buffer for narrow misty ghat roads and heavy rainfall.',
    badge: 'Living Root Bridges & Canyons',
    highlights: ['Nohkalikai & Seven Sisters waterfalls', 'Double Decker Living Root Bridge', 'Umngot River crystal boating Dawki', 'Mawlynnong cleanest village in Asia'],
    imageKey: 'corridor_north_east',
  },
  {
    slug: 'assam-wildlife-tea-river-island',
    region: CorridorRegion.NORTH_EAST,
    name: 'Assam Wildlife, Tea & River Island Trail',
    sortOrder: 27,
    durationMinDays: 6,
    durationMaxDays: 8,
    distanceKm: 490,
    stops: ['Guwahati', 'Kaziranga', 'Jorhat', 'Majuli', 'Sivasagar'],
    theme: 'Wildlife, tea gardens and Assamese heritage',
    description: 'Experience a guided Kaziranga safari, explore Majuli\'s satras and craft traditions, and visit Sivasagar\'s historic monuments. Assam Tourism publishes a similar Kaziranga–Majuli–Sivasagar circuit.',
    sourceName: 'Government Of Assam, India',
    sourceUrl: 'https://tourism.assam.gov.in',
    permits: ['Kaziranga National Park jeep safari pass'],
    advisoryNotes: 'Majuli river island involves vehicular ferry logistics. Confirm campervan height/weight restrictions at Nimati Ghat.',
    badge: 'Rhino Safari & River Island',
    highlights: ['One-horned rhino safari Kaziranga', 'Majuli mask-making & Vaishnavite Satras', 'Ahom dynasty Rang Ghar & Talatal Ghar', 'Historic Assam tea estate bungalows'],
    imageKey: 'corridor_north_east',
  },
  {
    slug: 'arunachal-himalayan-expedition',
    region: CorridorRegion.NORTH_EAST,
    name: 'Arunachal Himalayan Expedition',
    sortOrder: 28,
    durationMinDays: 8,
    durationMaxDays: 11,
    distanceKm: 520,
    stops: ['Guwahati', 'Bhalukpong', 'Dirang', 'Sela Pass', 'Tawang'],
    theme: 'High mountains, monasteries and dramatic passes',
    description: 'Travel through forested valleys and high-altitude scenery to Tawang Monastery and nearby mountain attractions. The Tawang district administration identifies permit requirements and seasonal access considerations.',
    sourceName: 'Arunachal Pradesh Tourism',
    sourceUrl: 'https://www.arunachaltourism.com',
    permits: ['Inner Line Permit (ILP) mandatory for all Indian citizens; PAP for foreign tourists'],
    advisoryNotes: 'Sela Pass is at 13,700 ft and can experience snow closures. Snow chains / winter preparation required in winter months.',
    badge: 'High Passes & Monasteries',
    highlights: ['13,700 ft Sela Pass & Lake', 'Tawang Monastery (India\'s largest)', 'Nuranang Waterfall Jang', 'Dirang valley apple & kiwi orchards'],
    imageKey: 'corridor_north_east',
  },
  {
    slug: 'sikkim-mountain-monastery-circuit',
    region: CorridorRegion.NORTH_EAST,
    name: 'Sikkim Mountain & Monastery Circuit',
    sortOrder: 29,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 390,
    stops: ['Siliguri', 'Gangtok', 'Rumtek', 'Tsomgo Lake', 'Namchi', 'Pelling'],
    theme: 'Himalayan viewpoints and Buddhist culture',
    description: 'Combine mountain panoramas, monasteries, local food and views of the Kanchenjunga range. Keep the route flexible for weather and road conditions.',
    sourceName: 'Sikkim Tourism',
    sourceUrl: 'https://www.sikkimtourism.gov.in',
    permits: ['Protected Area Permit (PAP) for Tsomgo Lake and Baba Mandir corridor'],
    advisoryNotes: 'Confirm high-altitude campervan entry permits for Tsomgo Lake 24 hours in advance at Gangtok tourism office.',
    badge: 'Kanchenjunga Panoramas',
    highlights: ['Glacial Tsomgo Lake at 12,310 ft', 'Rumtek Dharma Chakra Centre', 'Kanchenjunga morning view Pelling', 'Namchi Char Dham complex'],
    imageKey: 'corridor_north_east',
  },
  {
    slug: 'nagaland-hills-cultural-discovery',
    region: CorridorRegion.NORTH_EAST,
    name: 'Nagaland Hills & Cultural Discovery',
    sortOrder: 30,
    durationMinDays: 5,
    durationMaxDays: 7,
    distanceKm: 280,
    stops: ['Dimapur', 'Kohima', 'Khonoma', 'Kigwema', 'Dzukou Valley Base'],
    theme: 'Hill villages, local culture and trekking',
    description: 'Explore Kohima, traditional village architecture, local markets and trekking areas near Dzukou Valley. Arrange village visits and guided walks through local operators.',
    sourceName: 'Nagaland Tourism',
    sourceUrl: 'https://tourism.nagaland.gov.in',
    permits: ['Inner Line Permit (ILP) required for visiting Nagaland'],
    advisoryNotes: 'Dzukou Valley itself is a trekking trail. Park your campervan at the authorized Kigwema/Viswema base camp and continue on foot.',
    badge: 'Tribal Culture & Valley Treks',
    highlights: ['Khonoma Asia\'s first green village', 'Kohima Commonwealth War Memorial', 'Dzukou Valley base camp', 'Traditional Angami tribal architecture'],
    imageKey: 'corridor_north_east',
  },
];
